version: "2"
services:
  mariadb:
    build: ./mariadb/
    image: fuse_mariadb
    container_name: mariadb
    hostname: mariadb
    ports:
      - "33306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  base:
    build: ./base/
    image: ansible_base
  master:
    links:
      - base
    build: ./master/
    image: ansible_master
    container_name: master01
    hostname: master01
    command: ["/var/run.sh"]
    ports:
      - "2122:22"
      - "8101:8101"
      - "61616:61616"
      - "8181:8181"
    volumes:
      - ansible_vol:/usr/share/ansible
      - /.m2/repository:/u01/.m2/repository
  karaf01:
    links:
      - base
      - master
      - mariadb
    build: ./host/
    image: ansible_host
    container_name: karaf01
    hostname: karaf01
    command: ["/var/run.sh"]
    ports:
      - "2222:22"
      - "8201:8101"
      - "62616:61616"
      - "8281:8181"
    volumes:
      - ansible_vol:/usr/share/ansible
      - /.m2/repository:/u01/.m2/repository
  #karaf02:
  #  links:
  #    - base
  #    - master
  #    - karaf01
  #    - mariadb
  #  image: ansible_host
  #  container_name: karaf02
  #  hostname: karaf02
  #  command: ["/var/run.sh"]
  #  volumes:
  #   - ansible_vol:/usr/share/ansible 
volumes:
  mysql_data:
  ansible_vol:
