version: "2"
services:
  base:
    build: ./base/
    image: ansible_base
  master:
    links:
      - base
    build: ./master/
    image: ansible_master
    container_name: master01
    hostname: master01
    command: ["/usr/sbin/sshd","-D"]
    volumes:
      - ansible_vol:/usr/share/ansible
  karaf01:
    links:
      - base
      - master
    build: ./host/
    image: ansible_host
    container_name: karaf01
    hostname: karaf01
    command: ["/var/run.sh"]
    volumes:
     - ansible_vol:/usr/share/ansible
  #karaf02:
  #  links:
  #    - base
  #    - master
  #    - karaf01
  #  image: ansible_host
  #  container_name: karaf02
  #  hostname: karaf02
  #  command: ["/var/run.sh"]
  #  volumes:
  #   - ansible_vol:/usr/share/ansible 
volumes:
  ansible_vol: